### ISSUE TITLE
Sended Mails are not saved in correct IMAP-Folder

### ISSUE THREAD

**Issue by EifX** [absorb-it/Virtual-Identity#7] opened 2015-07-05 09:15 UTC
Hello,

yesterday, I've updated Thunderbird to version 38.0.1. Now, I have a problem with your extension. If I send a mail, the copy of the sended mail will not be saved in the "Sended"-Folder of my IMAP-Account. Instead of saving in the IMAP-Folder "Sended", Virtual-Identity saves the mail in the Local-Folders "Sended"-Folder.

My steps to reproduce:
- Download a fresh portable version of Thunderbird
- Install your addon
- Register my email-adress
- Send a mail

**Comment by absorb-it** [comment] 2015-07-06 16:19
Hi, many thanks for the report, the issue is fixed now in release 0.9.33.

**Closed as completed by absorb-it** 2015-07-06 16:19 UTC
